version: '3.8'

networks:
  threatguard-net:
    driver: bridge

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./api-gateway/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./api-gateway/dynamic.yml:/etc/traefik/dynamic.yml:ro"
    networks:
      - threatguard-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`localhost`) && PathPrefix(`/dashboard`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.services.dummy-service.loadbalancer.server.port=9999"

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - threatguard-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    networks:
      - threatguard-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    image: auth-service
    container_name: auth_service
    env_file:
      - .env
    networks:
      - threatguard-net
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8081/actuator/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5

  threat-service:
    image: threat-service
    container_name: threat_service
    env_file:
      - threat-service/.env
    networks:
      - threatguard-net
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  report-service:
    image: report-service
    container_name: report_service
    env_file:
      - report-service/.env
    networks:
      - threatguard-net
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8090/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: frontend
    container_name: frontend
    networks:
      - threatguard-net
    depends_on:
      - auth-service
      - threat-service
      - report-service

volumes:
  postgres_data: