apiVersion: v1
kind: Service
metadata:
  name: redis                     # threat-service se conecta a "redis:6379"
  namespace: threatguard
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP