apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: threatguard
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: NodePort             # NodePort expone el frontend hacia afuera del cluster
  # A diferencia de ClusterIP, NodePort es accesible desde tu máquina